CREATE DATABASE SIS;
USE SIS;
CREATE TABLE IF NOT EXISTS Student(
    StudentID INT AUTO_INCREMENT ,
    StFirstName VARCHAR(100) NOT NULL,
    StMidle VARCHAR(100) NOT NULL,
    StLastName VARCHAR(100) NOT NULL,
    Sex ENUM('M', 'F'),
    NRC VARCHAR(25) NOT NULL UNIQUE,
    PRIMARY KEY(StudentID)
);
CREATE TABLE IF NOT EXISTS Country(
    CountryID INT AUTO_INCREMENT,
    CountryName VARCHAR (100) UNIQUE NOT NULL,
    PRIMARY KEY(CountryID)

);
CREATE TABLE IF NOT EXISTS Province(
    ProvinceID INT AUTO_INCREMENT
    ProvinceName VARCHAR(100),
    PRIMARY KEY(ProvinceID)
);
CREATE TABLE IF NOT EXISTS City(
    CityID INT AUTO_INCREMENT NOT NULL,
    CityName VARCHAR(100) NOT NULL,
    

);
CREATE TABLE IF NOT EXISTS CLASS(
    ClASSID INT AUTO_INCREMENT,
    CLASSName VARCHAR(30) UNIQUE
);
CREATE TABLE IF NOT EXISTS Department(
    DepartmentID INT AUTO_INCREMENT NOT NULL,
    DepName VARCHAR(100) UNIQUE NOT NULL

);
CREATE TABLE IF NOT EXISTS Course(
    CourseId INT  AUTO_INCREMENT  NOT NULL,
    CourseName VARCHAR(100) NOT NULL,
    Duration  DECIMAL (15) NOT NULL
    
);
CREATE TABLE IF NOT EXISTS Subjects(
    SubjectID INT AUTO_INCREMENT,
    SubjName VARCHAR(100)
);
CREATE TABLE IF NOT EXISTS Assessment(
    AssessmentID INT AUTO_INCREMENT,
    TESTONE VARCHAR(10),
    TESTTWO VARCHAR(10),
    TESTTHREE VARCHAR(10),
    AsignmentOne varchar(10),
    AsignmentTwo varchar(10)
);
CREATE TABLE IF NOT EXISTS Lecturer(
    LectID INT AUTO_INCREMENT NOT NULL,
    LecFirstName VARCHAR(100) NOT NULL,
    LecMiddletName VARCHAR(100) NOT NULL,
    LecLastName VARCHAR(100) NOT NULL,
    LecTel VARCHAR(25) NOT NULL,
    Email VARCHAR(25) NOT NULL UNIQUE,
    Created TIMESTAMP default CURRENT_TIMESTAMP

);

