CREATE IF NOT EXISTS DATABASE SIS; /* THIS CODE IS NEEDED TO CREATE THE DATABASE IF IT DOES NOT EXIST IN THE SERVER */
USE SIS;
CREATE TABLE IF NOT EXISTS Student(/* CREATING THE TABLE FOR THE DATABASE*/
    StudentID INT AUTO_INCREMENT ,
    StFirstName VARCHAR(100) NOT NULL,
    StMidle VARCHAR(100) NOT NULL,
    StLastName VARCHAR(100) NOT NULL,
    Sex ENUM('M', 'F'),
    NRC VARCHAR(25) NOT NULL UNIQUE,
    PRIMARY KEY(StudentID)
    
);
/* CREATING TABLE  TO RECORDS STUDENT COUNTRY ORIGN */

CREATE TABLE IF NOT EXISTS Country(
    CountryID INT AUTO_INCREMENT,
    CountryName VARCHAR (100) UNIQUE NOT NULL,
    PRIMARY KEY(CountryID)

);
/* CREATING TABLE FOR STUDENT PROVINCE ORIGN*/
CREATE TABLE IF NOT EXISTS Province(
    ProvinceID INT AUTO_INCREMENT
    ProvinceName VARCHAR(100),
    PRIMARY KEY(ProvinceID)
);
/* CREATING TABLE FOR STUDENT CITY ORIGN*/
CREATE TABLE IF NOT EXISTS City(
    CityID INT AUTO_INCREMENT NOT NULL,
    CityName VARCHAR(100) NOT NULL,
    PRIMARY KEY(CityID)

);
/* CREATING TABLE FOR STUDENT ASSIGNED CLASS*/
CREATE TABLE IF NOT EXISTS Class(
    ClassID INT AUTO_INCREMENT,
    CLASSName VARCHAR(30) UNIQUE,
    PRIMARY KEY(ClassID)
);
/* CREATING TABLE FOR STUDENT DEPARTMENT*/
CREATE TABLE IF NOT EXISTS Department(
    DepartmentID INT AUTO_INCREMENT NOT NULL,
    DepName VARCHAR(100) UNIQUE NOT NULL,
    PRIMARY KEY(DepartmentID)
);
/* CREATING  COURSE TABLE FOR STUDENT*/
CREATE TABLE IF NOT EXISTS Course(
    CourseId INT  AUTO_INCREMENT  NOT NULL,
    CourseName VARCHAR(100) NOT NULL,
    Duration  DECIMAL (15) NOT NULL,
    PRIMARY KEY(CourseID)
);
/* CREATING COURSE SUBJECTS WHICH STUDENT WILL BE TAKING*/
CREATE TABLE IF NOT EXISTS Subjects(
    SubjectID INT AUTO_INCREMENT,
    SubjName VARCHAR(100),
    PRIMARY KEY(StudentID)
);
/* CREATING STUDENT ASSESSMENT TABLE FOR KEEPING RECORDS */
CREATE TABLE IF NOT EXISTS Assessment(
    AssessmentID INT AUTO_INCREMENT,
    TESTONE VARCHAR(10),
    TESTTWO VARCHAR(10),
    TESTTHREE VARCHAR(10),
    AsignmentOne varchar(10),
    AsignmentTwo varchar(10),
    PRIMARY KEY(AssessmentID)
);
/* CREATING TABLE FOR LECTURER THAT WILL BE TAKING TEACHING STUDENTS*/
CREATE TABLE IF NOT EXISTS Lecturer(
    LectID INT AUTO_INCREMENT NOT NULL,
    LecFirstName VARCHAR(100) NOT NULL,
    LecMiddletName VARCHAR(100) NOT NULL,
    LecLastName VARCHAR(100) NOT NULL,
    LecTel VARCHAR(25) NOT NULL,
    Email VARCHAR(25) NOT NULL UNIQUE,
    Created TIMESTAMP default CURRENT_TIMESTAMP,
    PRIMARY KEY(LectID
);
/* CREATING TABLE FOR RELIGIOUS AFFLIATION FOR EITHER STUDENT AND LECTURER*/
CREATE TABLE IF NOT EXISTS Religious(
    ReligiousID INT AUTO_INCREMENT NOT NULL,
    ReligiousName VARCHAR(100) NOT NULL UNIQUE,
    PRIMARY KEY(ReligiousID)
    );
/* CREATING TRIBE TABLE FOR EITHER STUDENT AND LECTURER*/

CREATE TABLE OF NOT EXISTS Tribe(
    TribeID INT AUTO_INCREMENT NOT NULL,
    TribeName VARCHAR (100),
    PRIMARY KEY(TribeID)
    );
CREATE TABLE IF NOT EXISTS Languages(
    LanguageID INT AUTO_INCREMENT NOT NULL,
    LanName VARCHAR (100) NOT NULL UNIQUE,
    FLUENT ENUM('Yes', 'No'),
    PRIMARY KEY(LanguageID)
    ):


